# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i0rJgAw6D5usK2mhWkAUqQIjNAeHJxst
"""

def kasallik_tashxisi(alomat):
  if alomat=="tomoq og'rig'i,yo'tal":
    return "Sizga laritilen ichishni tavfsiya beraman"
  elif alomat=="tish og'rig'i":
    return "Sizga fanigan tabletkasini tavfsiya beraman"
  elif alomat=="bosh og'rig'i":
    return "Sizga kyupen dorisini ichishni tavsiya beraman"
  elif alomat=="oshqozon og'rig'i":
    return "Sizga no-shpa dorisini tavsiya beraman"
  elif alomat=="bel og'rig'i" :
    return "Sizga Brufen dorisini tavfsiya beraman"
  elif alomat=="quloq og'rig'i":
    return "Sizga otipaks dorisini tavfsiya beraman"
  elif alomat=="Sevib qoldim" :
    return "battar bo'lin degan onamizni zo'r gaplaridan ichib olasiz"
  elif alomat=="rak kassaligi" :
    return "davosi yo'q"
  elif alomat=="oyoq og'rigi":
    return "Sizga inforin mazini tavfsiya beraman"
  elif alomat=="ko'ngil aynish" :
    return "Sizga Doprokin dorisini tavfsiya beraman"
  else:
    return "noaniq kasallik, shifokorga murojat qiling"
alomat=input("Alomatni kiriting")
natija=kasallik_tashxisi(alomat)
print(natija)